[package]
name = "rustyclient"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0.60"
tokio = { version = "^1.20.1", features = ["full"] }
tokio-stream = "^0.1.9"
#futures = "^0.3.21"
vhl_stdlib = { path = "../vhl_stdlib" }
